#!/usr/bin/env python3
# SPDX-License-Identifier: OPL-1.4
"""OPL NOTICE File Generator — Interactive CLI that creates a valid NOTICE file for Open-Pact License v1.4."""
import argparse
import os
import sys
import urllib.error
import urllib.request
from collections.abc import Callable

BANNER = r"""
  ___  ____  _     _____  ____ _  __
 / _ \/ __ \| |   |  ___|/ ___| |/ /
| | | | |_) | |   | |_  | |   | ' /
| |_| |  __/| |___|  _| | |___| . \
 \___/|_|   |_____|_|    \____|_|\_\

 NOTICE File Generator v1.4
"""

def ask(prompt: str, default: str | None = None, validator: Callable[[str], bool] | None = None,
        err_msg: str = "Invalid input.", allow_blank: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {prompt}{suffix}: ").strip()
        if not val and default is not None:
            val = default
        # allow_blank: an empty answer is valid (used for optional fields whose
        # prompt explicitly says 'blank = none' / 'skip').
        if (not val and allow_blank) or (val and (validator is None or validator(val))):
            return val
        print(f"  {err_msg}")

def validate_url(url: str) -> bool:
    return url.startswith("https://")

def validate_number(val: str, lo: int = 1, hi: int = 120) -> bool:
    try:
        n = int(val)
        return lo <= n <= hi
    except ValueError:
        return False

def validate_url_live(url: str) -> tuple[bool, str]:
    try:
        req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "OPL-Checker/1.0"})
        resp = urllib.request.urlopen(req, timeout=10)
        ct = resp.headers.get("Content-Type", "")
        if resp.status >= 400:
            return False, f"HTTP {resp.status}"
        if "text/html" not in ct and "text/plain" not in ct:
            return False, f"Content-Type is {ct}, expected HTML"
        return True, "OK"
    except Exception as e:
        return False, str(e)

def generate_notice(args: argparse.Namespace) -> str:
    lines = ["# NOTICE file for Open-Pact License v1.4", "# Generated by opl_init.py", "",
             f"OPL Version: {args.version}", f"Maintainer: {args.maintainer}",
             f"Governing Jurisdiction: {args.jurisdiction}",
             f"Standard Terms URL: {args.terms_url}", f"OPL-AI: {args.opl_ai}",
             # Always render the abandonment period so the adopter can see exactly
             # what they configured (F4: NOTICE was thin — the set value was hidden
             # whenever it matched the default of 36).
             f"Abandonment Period: {args.abandonment}"]
    if args.dosp:
        lines.append(f"DOSP Period: {args.dosp}")
    if args.commercial_terms:
        lines.append(f"Commercial Terms file: {args.commercial_terms}")
    if args.trademark:
        lines.append(f"Trademark Notice: {args.trademark}")
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_terms_template(args: argparse.Namespace) -> str:
    """F3: generate a ready-to-publish Standard Terms page (HTML) so the
    'publish your terms page' step is one action, not a void. The maintainer
    fills in pricing; the page states the OPL commercial-use contract in plain
    language a commercial user can act on."""
    model = args.commercial_model or "paid_standard_terms"
    model_label = {
        "paid_standard_terms": "Paid — standard terms (payment required for commercial use)",
        "free_for_all": "Free for all (commercial use permitted without payment)",
        "personal_only": "Personal / non-commercial only (commercial use prohibited)",
    }.get(model, model)
    opl_ai = ("opted in — AI training on this Work is restricted; do not train models on it."
              if args.opl_ai == "in" else "opted out — AI training is permitted unless stated elsewhere.")
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Standard Terms — {args.maintainer}</title>
  <style>body{{font-family:system-ui,sans-serif;max-width:48rem;margin:2rem auto;padding:0 1rem;line-height:1.6}}
  h1{{font-size:1.5rem}} .muted{{color:#666}} code{{background:#f4f4f4;padding:.1rem .3rem;border-radius:4px}}</style>
</head>
<body>
  <h1>Standard Terms for {args.maintainer}</h1>
  <p class="muted">This page is the <strong>Standard Terms URL</strong> referenced in this project's NOTICE file.
  It governs <strong>commercial use</strong> of software released under the Open-Pact License v{args.version}.</p>

  <h2>Commercial model</h2>
  <p>{model_label}</p>

  <h2>Pricing &amp; payment</h2>
  <p><!-- TODO: state your price and payment method. Examples: -->
     Commercial use requires a paid license. Contact <code>{args.maintainer}</code> or pay via
     <!-- Stripe / GitHub Sponsors / invoicing --> to obtain a commercial license.</p>

  <h2>Governing law</h2>
  <p>{args.jurisdiction}</p>

  <h2>AI training</h2>
  <p>{opl_ai}</p>

  <h2>Abandonment protection</h2>
  <p>If the Maintainer is unreachable for {args.abandonment} consecutive months, the Work
  automatically converts to Apache License 2.0 for all recipients — you are protected.</p>

  <hr>
  <p class="muted">Generated by <code>opl_init.py --terms-template</code>. Edit the pricing block before publishing.</p>
</body>
</html>
"""

def interactive_mode() -> argparse.Namespace:
    print(BANNER)
    print("  This wizard creates a NOTICE file for your OPL-1.4 project.\n")
    args = argparse.Namespace()
    args.version = "1.4"
    args.maintainer = ask("Maintainer name and email (e.g. Jane Doe <jane@example.com>)",
                          validator=lambda v: len(v) > 3, err_msg="Please provide a name and contact.")
    args.jurisdiction = ask(
        "Governing Jurisdiction (write your own — any jurisdiction; "
        "e.g. 'United States', 'Germany', 'Tokyo, Japan')", default="United States")
    print("\n  Standard Terms URL: a page where your commercial-use pricing lives.")
    print("  Must be HTTPS, return 2xx, serve HTML, and be readable without login.\n")
    args.terms_url = ask("Standard Terms URL (https://...)", validator=validate_url, err_msg="URL must start with https://")
    print("\n  Checking URL...")
    ok, msg = validate_url_live(args.terms_url)
    if ok:
        print(f"  URL check: {msg}")
    else:
        print(f"  WARNING: URL check failed: {msg}")
        print("  The NOTICE file will still be generated, but the URL may not be valid under OPL 3.3.")
    print("\n  OPL-AI Addendum: restricts AI training on your code (opt-in).")
    print("  Default is opted out — AI training is permitted.\n")
    ai = ask("Opt in to OPL-AI? (in/out)", default="out")
    args.opl_ai = ("opted in. AI training is restricted under the OPL-AI addendum (v1.4)."
                   if ai.lower().startswith("in") else "opted out.")
    print("\n  Abandonment period: months of unresponsiveness before Apache 2.0 conversion.")
    print("  CONSEQUENCE: if you go silent for this long, your Work automatically")
    print("  becomes Apache-2.0 (permissively licensed) for everyone — you lose")
    print("  the source-available restriction. Set longer if you want more grace.\n")
    args.abandonment = ask("Abandonment period in months (12-60)", default="36",
                           validator=lambda v: validate_number(v, 12, 60),
                           err_msg="Must be a number between 12 and 60.")
    print("\n  DOSP period (OPTIONAL, opt-in): months after each version's release on which")
    print("  that version's source converts to Apache 2.0. Leave blank for NO scheduled")
    print("  conversion (pure fair-source). Recommended 24-60; other values allowed.\n")
    print("  CONSEQUENCE: if you set, e.g., 36 months, then 3 years after you ship")
    print("  version 1.0, its source becomes Apache-2.0 for everyone — even if you never")
    print("  abandon the project. This is a scheduled, automatic release of your code.")
    print("  Leave blank to keep full source-available control indefinitely.\n")
    raw_dosp = ask("DOSP period in months (blank = none)", default="", allow_blank=True)
    args.dosp = raw_dosp if raw_dosp.strip() and validate_number(raw_dosp, 1, 120) else ""
    print("\n  Commercial Terms file (OPTIONAL): a per-version immutable file pinning your")
    print("  exact pricing/payment/scope, so enterprise users get a predictable contract.\n")
    print("  CONSEQUENCE: commercial users MUST pay per this published page. If the URL")
    print("  is dead or empty, OPL's commercial tier is unenforceable. You must actually")
    print("  publish a real pricing page before relying on paid commercial use.\n")
    args.commercial_terms = ask("Commercial Terms filename (blank = skip)", default="", allow_blank=True) or ""
    args.trademark = ask("Trademark notice (optional, press Enter to skip)", default="", allow_blank=True) or None
    return args

# Single source of truth for version: read from _version.py
from _version import __version__  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an OPL-1.4 NOTICE file.")
    parser.add_argument("--version", action="version", version=f"OPL Adoption Tools {__version__}")
    parser.add_argument("--non-interactive", action="store_true", help="Use CLI args instead of interactive prompts.")
    parser.add_argument("--output", default="NOTICE", help="Output file path (default: NOTICE).")
    parser.add_argument("--maintainer", help="Maintainer name and contact.")
    parser.add_argument("--jurisdiction", help="Governing jurisdiction.")
    parser.add_argument("--terms-url", help="Standard Terms URL.")
    parser.add_argument("--opl-ai", choices=["in", "out"], default="out", help="OPL-AI opt-in (default: out).")
    parser.add_argument("--abandonment", default="36", help="Abandonment period in months.")
    parser.add_argument("--dosp", help="DOSP period in months (optional, opt-in). Blank = no scheduled conversion.")
    parser.add_argument("--commercial-terms", help="Commercial Terms filename (optional).")
    parser.add_argument("--trademark", help="Trademark notice.")
    parser.add_argument("--commercial-model", choices=["paid_standard_terms", "free_for_all", "personal_only"],
                        default="paid_standard_terms",
                        help="Commercial model for the generated terms template.")
    parser.add_argument("--terms-template", action="store_true",
                        help="F3: generate a ready-to-publish Standard Terms HTML page instead of a NOTICE file.")
    cli = parser.parse_args()
    # F3: terms-template mode — generate a publishable Standard Terms page.
    if cli.terms_template:
        if not all([cli.maintainer, cli.jurisdiction, cli.terms_url]):
            print("ERROR: --maintainer, --jurisdiction, and --terms-url are required for --terms-template.")
            sys.exit(1)
        targs = argparse.Namespace(
            version=__version__, maintainer=cli.maintainer,
            jurisdiction=cli.jurisdiction, terms_url=cli.terms_url,
            opl_ai=cli.opl_ai, abandonment=cli.abandonment,
            commercial_model=cli.commercial_model)
        out = cli.output if cli.output != "NOTICE" else "standard-terms.html"
        with open(out, "w") as f:
            f.write(generate_terms_template(targs))
        print(f"\n  Standard Terms page written to {out}")
        print(f"  Edit the pricing block, then publish it at: {cli.terms_url}")
        return
    if cli.non_interactive:
        if not all([cli.maintainer, cli.jurisdiction, cli.terms_url]):
            print("ERROR: --maintainer, --jurisdiction, and --terms-url are required in non-interactive mode.")
            sys.exit(1)
        args = argparse.Namespace(
            version=__version__, maintainer=cli.maintainer,
            jurisdiction=cli.jurisdiction, terms_url=cli.terms_url,
            opl_ai=("opted in. AI training is restricted under the OPL-AI addendum (v"
                    + __version__ + ").") if cli.opl_ai == "in" else "opted out.",
            abandonment=cli.abandonment, dosp=cli.dosp or "",
            commercial_terms=cli.commercial_terms or "", trademark=cli.trademark)
    else:
        args = interactive_mode()
    content = generate_notice(args)
    out_path = cli.output
    if os.path.exists(out_path):
        if cli.non_interactive:
            pass  # non-interactive: explicit --output means overwrite is intended
        else:
            overwrite = input(f"  {out_path} already exists. Overwrite? (y/N): ").strip().lower()
            if overwrite != "y":
                print("  Aborted.")
                return
    with open(out_path, "w") as f:
        f.write(content)
    print(f"\n  NOTICE file written to {out_path}")
    # F4: echo back every optional field the adopter set so they can confirm
    # exactly what was captured (the NOTICE body always renders these too).
    set_fields = []
    if args.abandonment != "36":
        set_fields.append(f"Abandonment Period = {args.abandonment} months")
    if args.dosp:
        set_fields.append(f"DOSP Period = {args.dosp} months")
    if args.commercial_terms:
        set_fields.append(f"Commercial Terms file = {args.commercial_terms}")
    if args.trademark:
        set_fields.append(f"Trademark Notice = {args.trademark}")
    if set_fields:
        print("  Configured optional fields:")
        for f in set_fields:
            print(f"    - {f}")
    # F5: tell the adopter where the NOTICE belongs.
    print("  Place NOTICE at your repository root.")
    print("  Next steps:")
    print("    1. Publish your Standard Terms page at the URL you declared.")
    if args.commercial_terms:
        print(f"    2. Create {args.commercial_terms} with your pinned commercial terms "
              "(this wizard does not draft its contents).")
        print("    3. Add SPDX-License-Identifier: OPL-1.4 to each source file (use opl_spdx_inject.py).")
        print("    4. Run opl_check.py to validate your setup.")
    else:
        print("    2. Add SPDX-License-Identifier: OPL-1.4 to each source file (use opl_spdx_inject.py).")
        print("    3. Run opl_check.py to validate your setup.")

if __name__ == "__main__":
    main()
