#!/usr/bin/env python3
# SPDX-License-Identifier: OPL-1.4
"""OPL NOTICE File Generator — Interactive CLI that creates a valid NOTICE file for Open-Pact License v1.4."""
import argparse, os, re, sys, urllib.request, urllib.error
from typing import Any, Callable
import re
from pathlib import Path

VALID_JURISDICTIONS = ["California, United States", "Delaware, United States", "New York, United States", "England and Wales", "Ontario, Canada", "Berlin, Germany", "New South Wales, Australia", "Singapore", "Dublin, Ireland"]

BANNER = r"""
  ___  ____  _     _____  ____ _  __
 / _ \/ __ \| |   |  ___|/ ___| |/ /
| | | | |_) | |   | |_  | |   | ' /
| |_| |  __/| |___|  _| | |___| . \ 
 \___/|_|   |_____|_|    \____|_|\_\

 NOTICE File Generator v1.4
"""

def ask(prompt: str, default: str | None = None, validator: Callable[[str], bool] | None = None, err_msg: str = "Invalid input.") -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {prompt}{suffix}: ").strip()
        if not val and default is not None:
            val = default
        if val and (validator is None or validator(val)):
            return val
        print(f"  {err_msg}")

def validate_url(url: str) -> bool:
    return url.startswith("https://")

def validate_number(val: str, lo: int = 1, hi: int = 120) -> bool:
    try:
        n = int(val)
        return lo <= n <= hi
    except ValueError:
        return False

def validate_url_live(url: str) -> tuple[bool, str]:
    try:
        req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "OPL-Checker/1.0"})
        resp = urllib.request.urlopen(req, timeout=10)
        ct = resp.headers.get("Content-Type", "")
        if resp.status >= 400:
            return False, f"HTTP {resp.status}"
        if "text/html" not in ct and "text/plain" not in ct:
            return False, f"Content-Type is {ct}, expected HTML"
        return True, "OK"
    except Exception as e:
        return False, str(e)

def generate_notice(args: argparse.Namespace) -> str:
    lines = ["# NOTICE file for Open-Pact License v1.4", "# Generated by opl_init.py", "", f"OPL Version: {args.version}", f"Maintainer: {args.maintainer}", f"Governing Jurisdiction: {args.jurisdiction}", f"Standard Terms URL: {args.terms_url}", f"OPL-AI: {args.opl_ai}"]
    if args.abandonment != "36":
        lines.append(f"Abandonment Period: {args.abandonment}")
    if args.dosp:
        lines.append(f"DOSP Period: {args.dosp}")
    if args.commercial_terms:
        lines.append(f"Commercial Terms file: {args.commercial_terms}")
    if args.trademark:
        lines.append(f"Trademark Notice: {args.trademark}")
    lines.append("")
    return "\n".join(lines) + "\n"

def interactive_mode() -> argparse.Namespace:
    print(BANNER)
    print("  This wizard creates a NOTICE file for your OPL-1.4 project.\n")
    args = argparse.Namespace()
    args.version = "1.4"
    args.maintainer = ask("Maintainer name and email (e.g. Jane Doe <jane@example.com>)", validator=lambda v: len(v) > 3, err_msg="Please provide a name and contact.")
    print("\n  Common jurisdictions:")
    for i, j in enumerate(VALID_JURISDICTIONS, 1):
        print(f"    {i}. {j}")
    jur = ask("Governing Jurisdiction (number or custom text)", default="1")
    if jur.isdigit() and 1 <= int(jur) <= len(VALID_JURISDICTIONS):
        args.jurisdiction = VALID_JURISDICTIONS[int(jur) - 1]
    else:
        args.jurisdiction = jur
    print("\n  Standard Terms URL: a page where your commercial-use pricing lives.")
    print("  Must be HTTPS, return 2xx, serve HTML, and be readable without login.\n")
    args.terms_url = ask("Standard Terms URL (https://...)", validator=validate_url, err_msg="URL must start with https://")
    print("\n  Checking URL...")
    ok, msg = validate_url_live(args.terms_url)
    if ok:
        print(f"  URL check: {msg}")
    else:
        print(f"  WARNING: URL check failed: {msg}")
        print("  The NOTICE file will still be generated, but the URL may not be valid under OPL 3.3.")
    print("\n  OPL-AI Addendum: restricts AI training on your code (opt-in).")
    print("  Default is opted out — AI training is permitted.\n")
    ai = ask("Opt in to OPL-AI? (in/out)", default="out")
    args.opl_ai = "opted in. AI training is restricted under the OPL-AI addendum (v1.4)." if ai.lower().startswith("in") else "opted out."
    print("\n  Abandonment period: months of unresponsiveness before Apache 2.0 conversion.")
    args.abandonment = ask("Abandonment period in months (12-60)", default="36", validator=lambda v: validate_number(v, 12, 60), err_msg="Must be a number between 12 and 60.")
    print("\n  DOSP period (OPTIONAL, opt-in): months after each version's release on which")
    print("  that version's source converts to Apache 2.0. Leave blank for NO scheduled")
    print("  conversion (pure fair-source). Recommended 24-60; other values allowed.\n")
    raw_dosp = ask("DOSP period in months (blank = none)", default="")
    args.dosp = raw_dosp if raw_dosp and validate_number(raw_dosp, 1, 120) else ""
    print("\n  Commercial Terms file (OPTIONAL): a per-version immutable file pinning your")
    print("  exact pricing/payment/scope, so enterprise users get a predictable contract.\n")
    args.commercial_terms = ask("Commercial Terms filename (blank = skip)", default="") or ""
    args.trademark = ask("Trademark notice (optional, press Enter to skip)", default="") or None
    return args

# Single source of truth for version: read from _version.py
from _version import __version__  # noqa: E402

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an OPL-1.4 NOTICE file.")
    parser.add_argument("--version", action="version", version=f"OPL Adoption Tools {__version__}")
    parser.add_argument("--non-interactive", action="store_true", help="Use CLI args instead of interactive prompts.")
    parser.add_argument("--output", default="NOTICE", help="Output file path (default: NOTICE).")
    parser.add_argument("--maintainer", help="Maintainer name and contact.")
    parser.add_argument("--jurisdiction", help="Governing jurisdiction.")
    parser.add_argument("--terms-url", help="Standard Terms URL.")
    parser.add_argument("--opl-ai", choices=["in", "out"], default="out", help="OPL-AI opt-in (default: out).")
    parser.add_argument("--abandonment", default="36", help="Abandonment period in months.")
    parser.add_argument("--dosp", help="DOSP period in months (optional, opt-in). Blank = no scheduled conversion.")
    parser.add_argument("--commercial-terms", help="Commercial Terms filename (optional).")
    parser.add_argument("--trademark", help="Trademark notice.")
    cli = parser.parse_args()
    if cli.non_interactive:
        if not all([cli.maintainer, cli.jurisdiction, cli.terms_url]):
            print("ERROR: --maintainer, --jurisdiction, and --terms-url are required in non-interactive mode.")
            sys.exit(1)
        args = argparse.Namespace(version="1.4", maintainer=cli.maintainer, jurisdiction=cli.jurisdiction, terms_url=cli.terms_url, opl_ai="opted in. AI training is restricted under the OPL-AI addendum (v1.4)." if cli.opl_ai == "in" else "opted out.", abandonment=cli.abandonment, dosp=cli.dosp or "", commercial_terms=cli.commercial_terms or "", trademark=cli.trademark)
    else:
        args = interactive_mode()
    content = generate_notice(args)
    out_path = cli.output
    if os.path.exists(out_path):
        overwrite = input(f"  {out_path} already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("  Aborted.")
            return
    with open(out_path, "w") as f:
        f.write(content)
    print(f"\n  NOTICE file written to {out_path}")
    print("  Next steps:")
    print("    1. Publish your Standard Terms page at the URL you declared.")
    if args.commercial_terms:
        print(f"    2. Create {args.commercial_terms} with your pinned commercial terms (this wizard does not draft its contents).")
        print(f"    3. Add SPDX-License-Identifier: OPL-1.4 to each source file (use opl_spdx_inject.py).")
        print("    4. Run opl_check.py to validate your setup.")
    else:
        print("    2. Add SPDX-License-Identifier: OPL-1.4 to each source file (use opl_spdx_inject.py).")
        print("    3. Run opl_check.py to validate your setup.")

if __name__ == "__main__":
    main()
