#!/usr/bin/env python3
# SPDX-License-Identifier: OPL-1.3.1
"""x402 Payment Generator for OPL

Generates HTTP 402 payment integration code and configuration
for accepting crypto payments via the x402 protocol.

Usage:
    python3 opl_x402.py generate --framework fastapi --price 0.01 --asset USDC --chain base
    python3 opl_x402.py config --price 5.00 --asset USDC --chain base --recipient 0x...
    python3 opl_x402.py chains
    python3 opl_x402.py assets
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
import re

SUPPORTED_CHAINS = {
    "base": "Base (EVM)",
    "ethereum": "Ethereum Mainnet",
    "polygon": "Polygon (EVM)",
    "arbitrum": "Arbitrum (EVM)",
    "solana": "Solana",
    "optimism": "Optimism (EVM)",
    "avalanche": "Avalanche C-Chain",
}

SUPPORTED_ASSETS = {
    "USDC": "USD Coin",
    "USDT": "Tether USD",
    "DAI": "Dai Stablecoin",
    "EURC": "Euro Coin",
}

DEFAULT_RECIPIENT = "0x0000000000000000000000000000000000000000"


def validate_config(price: str, asset: str, chain: str) -> list[str]:
    errors: list[str] = []
    try:
        amount = float(price)
        if amount <= 0:
            errors.append(f"Price must be positive, got {price}")
    except ValueError:
        errors.append(f"Invalid price: {price}")
    if asset.upper() not in SUPPORTED_ASSETS:
        errors.append(f"Unsupported asset: {asset}. Use one of: {', '.join(SUPPORTED_ASSETS)}")
    if chain.lower() not in SUPPORTED_CHAINS:
        errors.append(f"Unsupported chain: {chain}. Use one of: {', '.join(SUPPORTED_CHAINS)}")
    return errors



# -- Framework-specific configuration for template generation ------------------
# Each entry provides the pieces that differ between frameworks.
# Strings = single lines; lists = multi-line blocks (unpacked with *).

_FRAMEWORKS = {
    "fastapi": {
        "docstring": "FastAPI x402 Payment Endpoint (generated by opl_x402.py)",
        "requirements": "pip install fastapi uvicorn",
        "imports": [
            "from fastapi import FastAPI, Request",
            "from fastapi.responses import JSONResponse",
        ],
        "app_init": "app = FastAPI()",
        "route_decorator": '@app.get("/api/data")',
        "func_sig": "async def get_data(request: Request):",
        "header_access": 'request.headers.get("x-payment-signature")',
        "response_402": [
            "        return JSONResponse(",
            "            status_code=402,",
            "            content={",
            '                "x402Version": 1,',
            '                "accepts": [{',
            '                    "network": X402["chain"],',
            '                    "maxAmountRequired": str(X402["price"]),',
            '                    "resource": "/api/data",',
            '                    "description": X402["description"],',
            '                    "mimeType": "application/json",',
            '                    "payTo": X402["payTo"],',
            '                    "extra": {},',
            "                }],",
            "            },",
            "        )",
        ],
        "verify_prefix": [
            "    # import httpx",
            "    # async with httpx.AsyncClient() as client:",
        ],
        "verify_call": [
            "    #         resp = await client.post(",
            "    #             f'{X402['facilitator_url']}/verify',",
            '    #             json={"paymentSignature": payment_signature},',
            "    #         )",
            "    #         if resp.status_code != 200:",
            '    #             return JSONResponse(status_code=402, content={"error": "Invalid payment"})',
        ],
        "success_return": '    return {"data": "Access granted!", "message": "Thank you for your payment."}',
        "main_block": [
            "",
            'if __name__ == "__main__":',
            "    import uvicorn",
            '    uvicorn.run(app, host="0.0.0.0", port=8000)',
        ],
    },
    "flask": {
        "docstring": "Flask x402 Payment Endpoint (generated by opl_x402.py)",
        "requirements": "pip install flask",
        "imports": [
            "from flask import Flask, request, jsonify",
        ],
        "app_init": "app = Flask(__name__)",
        "route_decorator": '@app.route("/api/data")',
        "func_sig": "def get_data():",
        "header_access": 'request.headers.get("x-payment-signature")',
        "response_402": [
            "        return jsonify({",
            '            "x402Version": 1,',
            '            "accepts": [{',
            '                "network": X402["chain"],',
            '                "maxAmountRequired": str(X402["price"]),',
            '                "resource": "/api/data",',
            '                "description": X402["description"],',
            '                "mimeType": "application/json",',
            '                "payTo": X402["payTo"],',
            '                "extra": {},',
            "            }],",
            "        }), 402",
        ],
        "verify_prefix": [
            "    # import requests",
            "    # resp = requests.post(",
        ],
        "verify_call": [
            "    #     f'{X402['facilitator_url']}/verify',",
            '    #     json={"paymentSignature": payment_signature},',
            "    # )",
            "    # if resp.status_code != 200:",
            '    #     return jsonify({"error": "Invalid payment"}), 402',
        ],
        "success_return": '    return jsonify({"data": "Access granted!", "message": "Thank you for your payment."})',
        "main_block": [
            "",
            'if __name__ == "__main__":',
            "    app.run(debug=True, port=5000)",
        ],
    },
}


def _build_endpoint_code(framework: str, price: float, asset: str,
                         chain: str, desc: str) -> str:
    """Build a payment endpoint file from a framework-specific config."""
    cfg = _FRAMEWORKS[framework]
    pay_to = "0x...YOUR_WALLET..."
    lines = [
        "#!/usr/bin/env python3",
        f'"""{cfg["docstring"]}"""',
        "",
        f"# Requirements: {cfg['requirements']}",
        "# For production: pip install x402  (Coinbase facilitator SDK)",
        "",
        *cfg["imports"],
        "",
        cfg["app_init"],
        "",
        "X402 = {",
        f'    "price": {price},',
        f'    "asset": "{asset}",',
        f'    "chain": "{chain}",',
        f'    "description": "{desc}",',
        f'    "payTo": "{pay_to}",',
        '    "facilitator_url": "https://x402.org/facilitator",',
        "}",
        "",
        "",
        cfg["route_decorator"],
        cfg["func_sig"],
        "    # Protected endpoint -- requires x402 payment.",
        f'    payment_signature = {cfg["header_access"]}',
        "",
        "    if not payment_signature:",
        *cfg["response_402"],
        "",
        "    # WARNING: Verification is NOT active in this template.",
        "    # Uncomment the code below and set up the x402 facilitator before deploying.",
        "    # Without verification, anyone can access this endpoint by providing any string.",
        "    #",
        "    # In production, verify with x402 facilitator:",
        *cfg["verify_prefix"],
        *cfg["verify_call"],
        "",
        cfg["success_return"],
        *cfg["main_block"],
    ]
    return "\n".join(lines) + "\n"


def _fastapi_code(price: float, asset: str, chain: str, desc: str) -> str:
    return _build_endpoint_code("fastapi", price, asset, chain, desc)


def _flask_code(price: float, asset: str, chain: str, desc: str) -> str:
    return _build_endpoint_code("flask", price, asset, chain, desc)

def generate_config(price: float, asset: str, chain: str,
                    recipient: str, description: str = "OPL commercial use") -> dict:
    return {
        "x402Version": 1,
        "config": {
            "price": price,
            "asset": asset,
            "network": chain,
            "payTo": recipient,
            "description": description,
            "facilitator": "https://x402.org/facilitator",
            "supportedChains": list(SUPPORTED_CHAINS.keys()),
            "supportedAssets": list(SUPPORTED_ASSETS.keys()),
        },
        "paymentChallenges": [
            {
                "network": chain,
                "maxAmountRequired": str(price),
                "resource": "/",
                "description": description,
                "mimeType": "application/json",
                "payTo": recipient,
                "extra": {},
            }
        ],
    }


# Single source of truth for version: read from __init__.py
try:
    from pathlib import Path
    _ns = {}
    exec((Path(__file__).resolve().parent / "__init__.py").read_text(), _ns)
    __version__ = _ns["__version__"]
except FileNotFoundError:
    raise SystemExit("ERROR: tools/__init__.py not found — cannot determine version")

def main() -> None:
    parser = argparse.ArgumentParser(
        description="x402 Payment Generator for OPL -- generates HTTP 402 crypto payment integration code")
    parser.add_argument("--version", action="version", version=f"OPL Adoption Tools {__version__}")
    sub = parser.add_subparsers(dest="command", help="Available commands")

    gen = sub.add_parser("generate", help="Generate a payment endpoint for a Python framework")
    gen.add_argument("--framework", choices=["fastapi", "flask"], default="fastapi",
                     help="Python framework (default: fastapi)")
    gen.add_argument("--price", required=True, help="Price per access (e.g. 0.01, 1.00)")
    gen.add_argument("--asset", default="USDC", help="Stablecoin (default: USDC)")
    gen.add_argument("--chain", default="base", help="Blockchain network (default: base)")
    gen.add_argument("--description", default="Premium content access",
                     help="Payment description")
    gen.add_argument("--output", help="Output file path (default: stdout)")

    cfg = sub.add_parser("config", help="Generate an x402 payment configuration JSON")
    cfg.add_argument("--price", required=True, help="Price per access (e.g. 0.01, 1.00)")
    cfg.add_argument("--asset", default="USDC", help="Stablecoin (default: USDC)")
    cfg.add_argument("--chain", default="base", help="Blockchain network (default: base)")
    cfg.add_argument("--recipient", default=DEFAULT_RECIPIENT,
                     help="Payment recipient address")
    cfg.add_argument("--description", default="OPL commercial use",
                     help="Payment description")
    cfg.add_argument("--output", help="Output file path (default: stdout)")

    sub.add_parser("chains", help="List supported chains")
    sub.add_parser("assets", help="List supported assets")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "generate":
        errors = validate_config(args.price, args.asset, args.chain)
        if errors:
            for e in errors:
                print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        price = float(args.price)
        gen_fn = _fastapi_code if args.framework == "fastapi" else _flask_code
        code = gen_fn(price, args.asset.upper(), args.chain.lower(), args.description)
        if args.output:
            Path(args.output).write_text(code)
            print(f"Generated {args.framework} endpoint -> {args.output}")
        else:
            print(code)

    elif args.command == "config":
        errors = validate_config(args.price, args.asset, args.chain)
        if errors:
            for e in errors:
                print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        if args.recipient == DEFAULT_RECIPIENT:
            print("WARNING: Using default zero-address as recipient. "
                  "Payments sent to the zero address will be unrecoverable. "
                  "Use --recipient to set your wallet address.", file=sys.stderr)
        config = generate_config(
            float(args.price), args.asset.upper(), args.chain.lower(),
            args.recipient, args.description)
        output = json.dumps(config, indent=2)
        if args.output:
            Path(args.output).write_text(output)
            print(f"Generated x402 config -> {args.output}")
        else:
            print(output)

    elif args.command == "chains":
        print("Supported chains:")
        for chain, name in SUPPORTED_CHAINS.items():
            print(f"  {chain:12s} {name}")

    elif args.command == "assets":
        print("Supported stablecoins:")
        for asset, name in SUPPORTED_ASSETS.items():
            print(f"  {asset:6s} {name}")


if __name__ == "__main__":
    main()
